global:
  # Global SMTP configuration
  smtp_smarthost: 'localhost:587'
  smtp_from: 'alerts@trademaster.com'
  smtp_auth_username: 'alerts@trademaster.com'
  smtp_auth_password: '${SMTP_PASSWORD}'
  smtp_require_tls: true

  # Slack configuration
  slack_api_url: '${SLACK_API_URL}'

  # PagerDuty configuration  
  pagerduty_url: 'https://events.pagerduty.com/v2/enqueue'

# Templates for notifications
templates:
  - '/etc/alertmanager/templates/*.tmpl'

# Routing tree
route:
  # Root route - catch all
  group_by: ['alertname', 'severity', 'service']
  group_wait: 10s
  group_interval: 5m
  repeat_interval: 4h
  receiver: 'platform-team'
  
  routes:
    # Critical alerts go to PagerDuty + Slack + Email
    - match:
        severity: critical
      receiver: 'critical-alerts'
      group_wait: 0s
      repeat_interval: 1h
      continue: true

    # Security alerts go to security team
    - match:
        team: security
      receiver: 'security-team'
      group_wait: 5s
      repeat_interval: 2h

    # Integration alerts go to integrations team  
    - match:
        team: integrations
      receiver: 'integrations-team'
      group_wait: 30s
      repeat_interval: 6h

    # Database alerts
    - match_re:
        alertname: 'Database.*|.*Database.*'
      receiver: 'database-team'
      group_wait: 15s
      repeat_interval: 3h

    # Performance alerts
    - match_re:
        alertname: '.*Performance.*|.*Latency.*|.*ResponseTime.*'
      receiver: 'performance-team'
      group_wait: 30s
      repeat_interval: 4h

    # Development environment - less urgent
    - match:
        environment: development
      receiver: 'dev-alerts'
      group_wait: 2m
      repeat_interval: 24h

# Alert inhibition rules
inhibit_rules:
  # If service is down, inhibit all other alerts for that service
  - source_match:
      alertname: 'BrokerAuthServiceDown'
    target_match:
      service: 'broker-auth'
    equal: ['service']

  # If there are critical errors, inhibit warning level alerts
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['service', 'alertname']

  # If there's a database issue, inhibit slow query alerts
  - source_match:
      alertname: 'DatabaseConnectionIssues'
    target_match:
      alertname: 'SlowDatabaseQueries'
    equal: ['service']

# Notification receivers
receivers:
  # Default platform team
  - name: 'platform-team'
    email_configs:
      - to: 'platform-team@trademaster.com'
        subject: '[TradeMaster] {{ .GroupLabels.alertname }} - {{ .GroupLabels.severity }}'
        body: |
          {{ range .Alerts }}
          **Alert:** {{ .Annotations.summary }}
          **Description:** {{ .Annotations.description }}
          **Service:** {{ .Labels.service }}
          **Severity:** {{ .Labels.severity }}
          **Dashboard:** {{ .Annotations.dashboard_url }}
          **Runbook:** {{ .Annotations.runbook_url }}
          **Started:** {{ .StartsAt }}
          {{ end }}
    slack_configs:
      - api_url: '${SLACK_API_URL}'
        channel: '#platform-alerts'
        title: 'TradeMaster Alert: {{ .GroupLabels.alertname }}'
        text: |
          {{ range .Alerts }}
          *{{ .Annotations.summary }}*
          {{ .Annotations.description }}
          Service: {{ .Labels.service }} | Severity: {{ .Labels.severity }}
          <{{ .Annotations.dashboard_url }}|Dashboard> | <{{ .Annotations.runbook_url }}|Runbook>
          {{ end }}

  # Critical alerts - multiple channels
  - name: 'critical-alerts'
    pagerduty_configs:
      - service_key: '${PAGERDUTY_SERVICE_KEY}'
        description: '{{ .GroupLabels.alertname }}: {{ range .Alerts }}{{ .Annotations.summary }}{{ end }}'
        details:
          service: '{{ .GroupLabels.service }}'
          severity: '{{ .GroupLabels.severity }}'
          dashboard: '{{ range .Alerts }}{{ .Annotations.dashboard_url }}{{ end }}'
          runbook: '{{ range .Alerts }}{{ .Annotations.runbook_url }}{{ end }}'
    email_configs:
      - to: 'critical-alerts@trademaster.com, platform-team@trademaster.com, cto@trademaster.com'
        subject: '[CRITICAL] TradeMaster {{ .GroupLabels.alertname }}'
        body: |
          🚨 CRITICAL ALERT 🚨
          
          {{ range .Alerts }}
          **Alert:** {{ .Annotations.summary }}
          **Description:** {{ .Annotations.description }}
          **Service:** {{ .Labels.service }}
          **Started:** {{ .StartsAt }}
          **Dashboard:** {{ .Annotations.dashboard_url }}
          **Runbook:** {{ .Annotations.runbook_url }}
          
          Immediate action required!
          {{ end }}
    slack_configs:
      - api_url: '${SLACK_API_URL}'
        channel: '#critical-alerts'
        color: 'danger'
        title: '🚨 CRITICAL: {{ .GroupLabels.alertname }}'
        text: |
          {{ range .Alerts }}
          *{{ .Annotations.summary }}*
          {{ .Annotations.description }}
          Service: {{ .Labels.service }}
          <{{ .Annotations.dashboard_url }}|📊 Dashboard> | <{{ .Annotations.runbook_url }}|📖 Runbook>
          {{ end }}

  # Security team
  - name: 'security-team'
    email_configs:
      - to: 'security-team@trademaster.com'
        subject: '[Security Alert] TradeMaster {{ .GroupLabels.alertname }}'
        body: |
          🛡️ SECURITY ALERT
          
          {{ range .Alerts }}
          **Alert:** {{ .Annotations.summary }}
          **Description:** {{ .Annotations.description }}
          **Service:** {{ .Labels.service }}
          **Severity:** {{ .Labels.severity }}
          **Started:** {{ .StartsAt }}
          **Runbook:** {{ .Annotations.runbook_url }}
          {{ end }}
    slack_configs:
      - api_url: '${SLACK_API_URL}'
        channel: '#security-alerts'
        color: 'warning'
        title: '🛡️ Security Alert: {{ .GroupLabels.alertname }}'

  # Integrations team
  - name: 'integrations-team'
    email_configs:
      - to: 'integrations-team@trademaster.com'
        subject: '[Integration Alert] TradeMaster {{ .GroupLabels.alertname }}'
        body: |
          🔌 INTEGRATION ALERT
          
          {{ range .Alerts }}
          **Alert:** {{ .Annotations.summary }}
          **Description:** {{ .Annotations.description }}
          **Service:** {{ .Labels.service }}
          **Started:** {{ .StartsAt }}
          **Runbook:** {{ .Annotations.runbook_url }}
          {{ end }}

  # Database team
  - name: 'database-team'
    email_configs:
      - to: 'dba-team@trademaster.com, platform-team@trademaster.com'
        subject: '[Database Alert] TradeMaster {{ .GroupLabels.alertname }}'
        body: |
          🗄️ DATABASE ALERT
          
          {{ range .Alerts }}
          **Alert:** {{ .Annotations.summary }}
          **Description:** {{ .Annotations.description }}
          **Service:** {{ .Labels.service }}
          **Started:** {{ .StartsAt }}
          **Runbook:** {{ .Annotations.runbook_url }}
          {{ end }}

  # Performance team
  - name: 'performance-team'
    email_configs:
      - to: 'performance-team@trademaster.com'
        subject: '[Performance Alert] TradeMaster {{ .GroupLabels.alertname }}'
        body: |
          ⚡ PERFORMANCE ALERT
          
          {{ range .Alerts }}
          **Alert:** {{ .Annotations.summary }}
          **Description:** {{ .Annotations.description }}
          **Service:** {{ .Labels.service }}
          **Started:** {{ .StartsAt }}
          **Dashboard:** {{ .Annotations.dashboard_url }}
          {{ end }}

  # Development environment - less urgent
  - name: 'dev-alerts'
    slack_configs:
      - api_url: '${SLACK_API_URL}'
        channel: '#dev-alerts'
        title: 'Dev Alert: {{ .GroupLabels.alertname }}'
        text: |
          {{ range .Alerts }}
          {{ .Annotations.summary }}
          Service: {{ .Labels.service }}
          {{ end }}