global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'trademaster-dev'
    region: 'us-east-1'

# Alertmanager configuration
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093
      timeout: 10s
      api_version: v2

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'
rule_files:
  - "/etc/prometheus/alerts/*.yml"

# Scrape configurations
scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 15s
    metrics_path: /metrics

  # TradeMaster Broker Auth Service
  - job_name: 'trademaster-broker-auth-service'
    static_configs:
      - targets: ['host.docker.internal:8080']  # Adjust port as needed
    scrape_interval: 10s
    metrics_path: /actuator/prometheus
    scrape_timeout: 10s
    honor_labels: true
    params:
      format: ['prometheus']
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: host.docker.internal:8080

  # Node Exporter for system metrics
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 15s
    relabel_configs:
      - source_labels: [__address__]
        regex: '(.*):(.*)'
        target_label: instance
        replacement: '${1}'

  # cAdvisor for container metrics
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    scrape_interval: 15s
    metrics_path: /metrics
    relabel_configs:
      - source_labels: [__name__]
        regex: 'container_.*'
        target_label: __tmp_container_metric
      - source_labels: [__tmp_container_metric]
        regex: '.+'
        target_label: __keep
        replacement: 'true'

  # Alertmanager
  - job_name: 'alertmanager'
    static_configs:
      - targets: ['alertmanager:9093']
    scrape_interval: 15s

  # Grafana
  - job_name: 'grafana'
    static_configs:
      - targets: ['grafana:3000']
    scrape_interval: 15s
    metrics_path: /metrics

  # PostgreSQL Exporter (if deployed separately)
  - job_name: 'postgres-exporter'
    static_configs:
      - targets: ['postgres-exporter:9187']
    scrape_interval: 15s
    scrape_timeout: 10s

  # Redis Exporter (if deployed separately)  
  - job_name: 'redis-exporter'
    static_configs:
      - targets: ['redis-exporter:9121']
    scrape_interval: 15s

  # Jaeger metrics
  - job_name: 'jaeger'
    static_configs:
      - targets: ['jaeger:14269']
    scrape_interval: 15s
    metrics_path: /metrics

  # Custom application metrics endpoint
  - job_name: 'broker-auth-business-metrics'
    static_configs:
      - targets: ['host.docker.internal:8080']
    scrape_interval: 5s  # More frequent for business metrics
    metrics_path: /actuator/prometheus
    params:
      match[]: 
        - '{__name__=~"broker_.*"}'
        - '{__name__=~"security_.*"}'
        - '{__name__=~"authentication_.*"}'
    honor_labels: true

# Storage configuration
storage:
  tsdb:
    path: /prometheus
    retention.time: 30d
    retention.size: 50GB
    wal-compression: true

# Remote write configuration (for long-term storage)
# remote_write:
#   - url: "https://your-long-term-storage/api/v1/write"
#     basic_auth:
#       username: "prometheus"
#       password: "your-password"

# Global limits
global:
  scrape_timeout: 10s
  evaluation_interval: 15s
  external_labels:
    monitor: 'trademaster-monitor'
    environment: 'development'